### PR TITLE
feat(babel): Update rollup + babel config

### PR DESCRIPTION
**Pull request by HeadFox**
Hi again :)
Wa had some issue with your library and IE 11. It was caused by the default param value that isn't supported on IE.
I also took this occasion to update a little bit you configuration.

## Changelog
* Update rollup & @rollup/plugin-commonjs packages
* Update @babel/core & @babel/preset-env packages
* Update rollup config to add babel plugin.
* Set preset-env config to default to support ie11
* Add esm bundled file

### CODE REVIEW

**Comment by andrewmclagan** [comment]
ah... this will be an issue. We have a policy of not supporting any version of IE. We believe that supporting such platforms simply extends their life. Most of this PR is great, but the changes to syntax to support IE wont be accepted - sorry!

**Comment by HeadFox** [comment]
I completely agree with and we planned to drop it also but still too many user use it and it's a company decision to make.
We hope it will be decide this year ! :) 

If I adapt your configuration to create a separate JS file for IE (that we will need to import manually like ´react-env/dist/or-build.js´) is it okey for you ? 
If not we will continue to update our fork until we finally drop IE !

**Comment by andrewmclagan** [comment]
Yeah sorry, cant accept any IE specific changes. It will only create a new point of maintenance. :-( seriously i know its a hard call and your contributions are super appreciated... 

But yes this will be accepted without those changes!

PS new release is out with all the changes https://github.com/andrewmclagan/react-env/releases/tag/3.1.0

**Comment by HeadFox** [comment]
Not a problem ! :) Completely agree with your way of thinking ! 
I will edit my PR today. 
Thanks for the release 👌

**Comment by HeadFox** [comment]
@andrewmclagan removed IE support in my last two commit ! 
I will autosquash, rebase and force push after you approve :)

**Comment by HeadFox** [comment]
Ready to be merge ! :)

**Pull request closed without merging**
